on:
  workflow_call:
    inputs:
      ENV:
        type: string
        required: true
      Hoge:
        type: boolean
        required: true
        

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: test1
        if: ${{ inputs.ENV == 'prd' }}
        run: echo true

      - name: test2
        if: ${{ inputs.Hoge }}
        run: echo true

      - name: test3
        run: echo ${{ inputs.Hoge }}
